In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [3]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
listarray.dtype

dtype('int32')

In [5]:
listarray.shape

(3, 3)

In [6]:
listarray.size

9

In [7]:
listarray[0,1]= 22

In [8]:
listarray

array([[ 1, 22,  3],
       [ 4,  5,  6],
       [ 6,  7,  8]])

In [9]:
zeros = np.zeros((3,4))

In [10]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
zeros.dtype

dtype('float64')

In [12]:
zeros.shape

(3, 4)

In [13]:
zeros.size

12

In [14]:
range = np.arange(10)

In [15]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
lins= np.linspace(1,4,4)

In [17]:
lins

array([1., 2., 3., 4.])

In [18]:
emp= np.empty((4,4))

In [19]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56599128e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

In [20]:
a=np.identity(45)

In [21]:
a

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
b=np.arange(99)

In [23]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
b.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])


# axis

In [27]:
x=([1,2,3],[5,6,7],[8,9,0])

In [28]:
arr = np.array(x)

In [29]:
arr

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [30]:
arr.sum(axis=0)

array([14, 17, 10])

In [31]:
arr.sum(axis=1)

array([ 6, 18, 17])

In [32]:
arr.T

array([[1, 5, 8],
       [2, 6, 9],
       [3, 7, 0]])

In [33]:
arr.flat

In [34]:
for items in arr.flat:
    print(items)

1
2
3
5
6
7
8
9
0


In [35]:
arr.ndim

2

In [36]:
arr.nbytes

36

In [37]:
c=np.array([1,35,634,4])

In [38]:
c.argmax()

2

In [39]:
c.argmin()

0

In [40]:
c.argsort()

array([0, 3, 1, 2], dtype=int64)

In [41]:
arr

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [42]:
arr.argmax()

7

In [43]:
arr.argmin()

8

In [44]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [45]:
#if
arr.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [46]:
 arr.argmin(axis = 1)

array([0, 0, 2], dtype=int64)

In [47]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [48]:
arr

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [49]:
arr2 = np.array([[4,5,6],[7,8,9],[10,11,12]])
arr2

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr + arr2

array([[ 5,  7,  9],
       [12, 14, 16],
       [18, 20, 12]])

In [51]:
[19,10]+[13,45]

[19, 10, 13, 45]

In [52]:
arr*arr2

array([[ 4, 10, 18],
       [35, 48, 63],
       [80, 99,  0]])

In [53]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 0.        ]])

In [54]:
np.sqrt(arr2)

array([[2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [55]:
arr.sum()

41

In [56]:
arr2.max()

12

In [57]:
arr2.min()

4

In [58]:
np.where(arr>5)

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 0, 1], dtype=int64))

In [59]:
np.count_nonzero(arr)

8